### ISSUE TITLE
Commits lost in rebase

### ISSUE THREAD

**Issue by LiptonB** [shellphish/driller#60]
It appears the driller repo was rebased recently, and some of the commits on the previous master branch are missing from the current one. Is that intentional? The commits in question can be seen here: https://github.com/shellphish/driller/compare/master...3e974f67d33004ff08d4549e4193772d4a6e2231

**Comment by rhelmot** [comment]
From what I can tell, this happened during the the_end_times refactor last year, during the solver API refactor? It's hard to tell if that's actually what caused it or if it was during the new_files refactor and I was just impatient with some branches... Either way, I can't find the culprit in my reflog...

I can't seem to cherry-pick these changes because the files have been renamed, so I'm going to manually redo the changes and commit with the appropriate authorship.

**Comment by rhelmot** [comment]
As far as I can tell everything is fixed.

https://github.com/shellphish/driller/commit/7af797a45491b5cbe8b6fe793dfd619425813a1c
https://github.com/shellphish/driller/commit/14ae950ea5ef8c413b043f15e13ec13011085812
https://github.com/angr/angr/commit/480ff267e65ccc2727e5a43a6b4a9fe7d36194ba
https://github.com/angr/angr/commit/a57703d03aa2e218a2ee2de1a12ae9ee2c403a5d
